from enum import Enum


class Stddev(str, Enum):
    FIRST_ABOVE = "FIRST_STDDEV_ABOVE"
    SECOND_ABOVE = "SECOND_STDDEV_ABOVE"
    THIRD_ABOVE = "THIRD_STDDEV_ABOVE"
    FIRST_BELOW = "FIRST_STDDEV_BELOW"
    SECOND_BELOW = "SECOND_STDDEV_BELOW"
    THIRD_BELOW = "THIRD_STDDEV_BELOW"


LEVEL_UP_TRIGGER = "LEVEL_UP_TRIGGER"


